# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Contacts' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for Contacts
  pod 'MagicalRecord', '~>2.3.2'


  target 'ContactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
